from model.skill import Skill
from model.skill import Category

skills = [
    Skill(id=0, mentor=0, category=Category.LIFE, title="How to Change a Tire", description="I'll teach you how to change a car tire."),
    Skill(id=1, mentor=0, category=Category.MUSIC, title="How to Play Free Bird Solo", description="I'll teach you how to play the Free Bird solo on guitar."),
    Skill(id=2, mentor=0, category=Category.MATH, title="The Pythagorean Theorem", description="I'll teach you the Pythagorean theorem so it's easy to understand."),
    Skill(id=3, mentor=0, category=Category.SCIENCE, title="Explaining Evolution", description="Learn evolution from a certified biologist."),
    Skill(id=4, mentor=1, category=Category.HISTORY, title="Life in the Middle Ages", description="Find out what life was like in 600 AD."),
    Skill(id=5, mentor=1, category=Category.LIFE, title="Need Tax Help?", description="I'll file your taxes!"),
    Skill(id=6, mentor=1, category=Category.MATH, title="Calculus 101", description="I'll give you a tutor lesson for Calculus 101."),
    Skill(id=7, mentor=1, category=Category.MUSIC, title="Voice Lesson", description="Get a voice lesson from a professional Broadway singer."),
    Skill(id=8, mentor=0, category=Category.LIFE, title="Meal Prepping for Busy People", description="I'll show you how to meal prep for the week in under 2 hours."),
    Skill(id=9, mentor=0, category=Category.MUSIC, title="Intro to Piano Chords", description="Learn the basic chords to start playing piano today."),
    Skill(id=10, mentor=0, category=Category.MATH, title="Intro to Statistics", description="Understand basic statistical concepts like mean, median, and standard deviation."),
    Skill(id=11, mentor=0, category=Category.SCIENCE, title="Understanding Climate Change", description="A practical guide to understanding the science of climate change."),
    Skill(id=12, mentor=1, category=Category.HISTORY, title="The Cold War Explained", description="An overview of the Cold War and its global impact."),
    Skill(id=13, mentor=1, category=Category.LIFE, title="Declutter Your Home", description="Learn minimalist strategies to tidy up your living space."),
    Skill(id=14, mentor=1, category=Category.MATH, title="Learn Basic Algebra", description="Step-by-step help for learning how to solve equations."),
    Skill(id=15, mentor=1, category=Category.MUSIC, title="Write Your First Song", description="I'll help you write and structure your first original song."),
    Skill(id=16, mentor=2, category=Category.LIFE, title="Time Management Tips", description="Learn to manage your day efficiently."),
    Skill(id=17, mentor=2, category=Category.MUSIC, title="Jazz Improvisation", description="Master the basics of jazz soloing."),
    Skill(id=18, mentor=2, category=Category.MATH, title="Trigonometry Basics", description="Learn sine, cosine, and tangent easily."),
    Skill(id=19, mentor=2, category=Category.SCIENCE, title="Basics of Genetics", description="Understand genes, alleles, and inheritance."),
    Skill(id=20, mentor=2, category=Category.HISTORY, title="Ancient Egypt 101", description="Explore the culture and achievements of Ancient Egypt."),
    Skill(id=21, mentor=3, category=Category.LIFE, title="Healthy Grocery Shopping", description="Learn how to shop smart and eat healthy."),
    Skill(id=22, mentor=3, category=Category.MUSIC, title="Ukulele for Beginners", description="Get started playing ukulele in minutes."),
    Skill(id=23, mentor=3, category=Category.MATH, title="Understanding Fractions", description="I'll help you master fractions and ratios."),
    Skill(id=24, mentor=3, category=Category.SCIENCE, title="What is Quantum Physics?", description="An intro to the weird world of quantum mechanics."),
    Skill(id=25, mentor=3, category=Category.HISTORY, title="History of Feminism", description="Learn how feminist movements shaped the world."),
    Skill(id=26, mentor=4, category=Category.LIFE, title="Beginner's Guide to Meditation", description="I'll help you build a simple meditation habit."),
    Skill(id=27, mentor=4, category=Category.MUSIC, title="Singing Harmonies", description="Learn how to sing harmonies in any genre."),
    Skill(id=28, mentor=4, category=Category.MATH, title="Graphing Equations", description="Understand how to draw graphs from equations."),
    Skill(id=29, mentor=4, category=Category.SCIENCE, title="The Periodic Table", description="Get comfortable navigating the periodic table."),
    Skill(id=30, mentor=4, category=Category.HISTORY, title="World War I Overview", description="A digestible overview of WWI and its causes."),
    Skill(id=31, mentor=5, category=Category.LIFE, title="How to Budget", description="I'll show you how to set up a realistic budget."),
    Skill(id=32, mentor=5, category=Category.MUSIC, title="Making Beats in FL Studio", description="Learn how to make your first beat."),
    Skill(id=33, mentor=5, category=Category.MATH, title="Multiplication Tricks", description="Easy techniques to speed up mental math."),
    Skill(id=34, mentor=5, category=Category.SCIENCE, title="Photosynthesis Explained", description="Understand how plants make their food."),
    Skill(id=35, mentor=5, category=Category.HISTORY, title="American Civil Rights Movement", description="Explore key events and figures."),
    Skill(id=36, mentor=6, category=Category.LIFE, title="Organizing Your Workspace", description="Tips for decluttering and productivity."),
    Skill(id=37, mentor=6, category=Category.MUSIC, title="Reading Sheet Music", description="Learn the basics of music notation."),
    Skill(id=38, mentor=6, category=Category.MATH, title="Word Problems Made Easy", description="Strategies to tackle math word problems."),
    Skill(id=39, mentor=6, category=Category.SCIENCE, title="Simple Machines", description="Learn the six basic types of simple machines."),
    Skill(id=40, mentor=6, category=Category.HISTORY, title="Colonial America", description="What life was like in the original 13 colonies."),
    Skill(id=41, mentor=7, category=Category.LIFE, title="First Apartment Essentials", description="Everything you need when moving out."),
    Skill(id=42, mentor=7, category=Category.MUSIC, title="Intro to Music Theory", description="Chords, scales, and how songs are built."),
    Skill(id=43, mentor=7, category=Category.MATH, title="Geometry Foundations", description="Learn shapes, angles, and how to measure them."),
    Skill(id=44, mentor=7, category=Category.SCIENCE, title="States of Matter", description="Solids, liquids, gases, and plasma explained."),
    Skill(id=45, mentor=7, category=Category.HISTORY, title="Renaissance Art & Culture", description="Discover the artists and thinkers of the era."),
    Skill(id=46, mentor=8, category=Category.LIFE, title="How to Write a Resume", description="Craft a resume that gets attention."),
    Skill(id=47, mentor=8, category=Category.MUSIC, title="How to Tune a Guitar", description="Learn to tune by ear or with a tuner."),
    Skill(id=48, mentor=8, category=Category.MATH, title="Math for Everyday Life", description="Apply math to tipping, taxes, and budgeting."),
    Skill(id=49, mentor=8, category=Category.SCIENCE, title="What is a Black Hole?", description="Understand how black holes form and behave."),
    Skill(id=50, mentor=8, category=Category.HISTORY, title="Fall of the Roman Empire", description="Why did the empire fall, and what came next?"),
    Skill(id=51, mentor=9, category=Category.LIFE, title="How to Do Laundry", description="A beginner's guide to laundry and sorting."),
    Skill(id=52, mentor=9, category=Category.MUSIC, title="Drumming Basics", description="Learn your first beat and rhythm."),
    Skill(id=53, mentor=9, category=Category.MATH, title="Probability for Beginners", description="Dice, coins, and real-life probabilities."),
    Skill(id=54, mentor=9, category=Category.SCIENCE, title="The Scientific Method", description="How scientists ask questions and find answers."),
    Skill(id=55, mentor=9, category=Category.HISTORY, title="Industrial Revolution", description="How machines reshaped society."),
    Skill(id=56, mentor=10, category=Category.LIFE, title="How to Cook Rice", description="Perfect rice on the stove, every time."),
    Skill(id=57, mentor=10, category=Category.MUSIC, title="Writing a Pop Hook", description="Catchy melodies that get stuck in your head."),
    Skill(id=58, mentor=10, category=Category.MATH, title="Decimals & Percentages", description="Convert and calculate percentages easily."),
    Skill(id=59, mentor=10, category=Category.SCIENCE, title="Intro to Astronomy", description="Tour the solar system and beyond."),
    Skill(id=60, mentor=10, category=Category.HISTORY, title="The French Revolution", description="Liberté, égalité, fraternité – and guillotines."),
    Skill(id=61, mentor=11, category=Category.LIFE, title="Basic Car Maintenance", description="Learn how to check oil, tire pressure, and fluids."),
    Skill(id=62, mentor=11, category=Category.MUSIC, title="Intro to Piano Chords", description="Understand how to build and play basic chords."),
    Skill(id=63, mentor=11, category=Category.SCIENCE, title="Climate Change 101", description="Understand the science and impacts of climate change.")
]